<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260907180857 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "Assunto" ("codAs" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "Descricao" VARCHAR(20) NOT NULL, PRIMARY KEY ("codAs"))');
        $this->addSql('CREATE TABLE "Autor" ("CodAu" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "Nome" VARCHAR(40) NOT NULL, PRIMARY KEY ("CodAu"))');
        $this->addSql('CREATE TABLE "Livro" ("Codl" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "Titulo" VARCHAR(40) NOT NULL, "Editora" VARCHAR(40) NOT NULL, "Edicao" INT NOT NULL, "AnoPublicacao" VARCHAR(4) NOT NULL, "Valor" NUMERIC(10, 2) NOT NULL, PRIMARY KEY ("Codl"))');
        $this->addSql('CREATE TABLE "Livro_Autor" ("Livro_Codl" INT NOT NULL, "Autor_CodAu" INT NOT NULL, PRIMARY KEY ("Livro_Codl", "Autor_CodAu"))');
        $this->addSql('CREATE INDEX IDX_41293941BC754E79 ON "Livro_Autor" ("Livro_Codl")');
        $this->addSql('CREATE INDEX IDX_412939416FEF0A9C ON "Livro_Autor" ("Autor_CodAu")');
        $this->addSql('CREATE TABLE "Livro_Assunto" ("Livro_Codl" INT NOT NULL, "Assunto_codAs" INT NOT NULL, PRIMARY KEY ("Livro_Codl", "Assunto_codAs"))');
        $this->addSql('CREATE INDEX IDX_2F01B743BC754E79 ON "Livro_Assunto" ("Livro_Codl")');
        $this->addSql('CREATE INDEX IDX_2F01B743CFE2DBD9 ON "Livro_Assunto" ("Assunto_codAs")');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE "Livro_Autor" ADD CONSTRAINT FK_41293941BC754E79 FOREIGN KEY ("Livro_Codl") REFERENCES "Livro" ("Codl") NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "Livro_Autor" ADD CONSTRAINT FK_412939416FEF0A9C FOREIGN KEY ("Autor_CodAu") REFERENCES "Autor" ("CodAu") NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "Livro_Assunto" ADD CONSTRAINT FK_2F01B743BC754E79 FOREIGN KEY ("Livro_Codl") REFERENCES "Livro" ("Codl") NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "Livro_Assunto" ADD CONSTRAINT FK_2F01B743CFE2DBD9 FOREIGN KEY ("Assunto_codAs") REFERENCES "Assunto" ("codAs") NOT DEFERRABLE');

        $this->addSql('
        CREATE OR REPLACE VIEW vw_relatorio_livros AS
        SELECT 
            a."CodAu" AS autor_id,
            a."Nome" AS autor_nome,
            l."Codl" AS livro_id,
            l."Titulo" AS livro_titulo,
            l."Editora" AS livro_editora,
            l."Edicao" AS livro_edicao,
            l."AnoPublicacao" AS livro_ano_publicacao,
            l."Valor" AS livro_valor,
            s."codAs" AS assunto_id,
            s."Descricao" AS assunto_descricao
        FROM "Autor" a
        INNER JOIN "Livro_Autor" la ON la."Autor_CodAu" = a."CodAu"
        INNER JOIN "Livro" l ON l."Codl" = la."Livro_Codl"
        LEFT JOIN "Livro_Assunto" ls ON ls."Livro_Codl" = l."Codl"
        LEFT JOIN "Assunto" s ON s."codAs" = ls."Assunto_codAs"
        ');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE "Livro_Autor" DROP CONSTRAINT FK_41293941BC754E79');
        $this->addSql('ALTER TABLE "Livro_Autor" DROP CONSTRAINT FK_412939416FEF0A9C');
        $this->addSql('ALTER TABLE "Livro_Assunto" DROP CONSTRAINT FK_2F01B743BC754E79');
        $this->addSql('ALTER TABLE "Livro_Assunto" DROP CONSTRAINT FK_2F01B743CFE2DBD9');
        $this->addSql('DROP TABLE "Assunto"');
        $this->addSql('DROP TABLE "Autor"');
        $this->addSql('DROP TABLE "Livro"');
        $this->addSql('DROP TABLE "Livro_Autor"');
        $this->addSql('DROP TABLE "Livro_Assunto"');
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('DROP VIEW IF EXISTS vw_relatorio_livros');
    }
}
